# Generated by Django 5.2.7 on 2026-03-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='HTML allowed', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='About Villa Grande', max_length=200)),
                ('description', models.TextField()),
                ('image_main', models.ImageField(upload_to='about/')),
                ('image_accent', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('years_of_excellence', models.PositiveIntegerField(default=15)),
                ('button_text', models.CharField(default='Discover Our Story', max_length=50)),
                ('button_link', models.CharField(default='lodge:about', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='HTML allowed', max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(help_text='YouTube or Vimeo embed URL')),
                ('background_image', models.ImageField(upload_to='experience/')),
                ('button_one_text', models.CharField(default='Our Rooms', max_length=50)),
                ('button_one_link', models.CharField(default='lodge:rooms', max_length=200)),
                ('button_two_text', models.CharField(default='Book a Stay', max_length=50)),
                ('button_two_link', models.CharField(default='lodge:booking', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='HTML allowed, e.g. Experience <em>Refined</em> Comfort', max_length=200)),
                ('subtitle', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='hero/')),
                ('button_text', models.CharField(default='Explore Rooms', max_length=50)),
                ('button_link', models.CharField(default='lodge:rooms', help_text='Django URL name, e.g. lodge:rooms', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='HTML allowed', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('placeholder_text', models.CharField(default='Enter your email address', max_length=100)),
                ('button_text', models.CharField(default='Subscribe', max_length=50)),
                ('privacy_link', models.CharField(default='#', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('icon', models.CharField(choices=[('fa-hotel', 'Hotel'), ('fa-utensils', 'Restaurant'), ('fa-spa', 'Spa'), ('fa-swimming-pool', 'Pool'), ('fa-glass-cheers', 'Events'), ('fa-concierge-bell', 'Concierge'), ('fa-wifi', 'Wi-Fi'), ('fa-dumbbell', 'Gym'), ('fa-car', 'Parking'), ('fa-shuttle-van', 'Shuttle')], default='fa-hotel', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, help_text='e.g. +, %, K', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='lodge.aboutsection')),
            ],
            options={
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
    ]
