# Generated by Django 5.2.7 on 2026-03-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0002_aboutsection_experiencesection_heroslide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Villa Grande', max_length=100)),
                ('tagline', models.CharField(default='Luxury Lodge', max_length=200)),
                ('address', models.TextField(help_text='Full physical address')),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number', max_length=30)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Site logo (optional)', null=True, upload_to='site/')),
                ('copyright_text', models.CharField(default='© {year} Villa Grande Lodge. All rights reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
