# Generated by Django 5.2.7 on 2026-03-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
