# Generated by Django 5.2.15 on 2026-07-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0005_booking_booking_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='Font Awesome class, e.g., fas fa-wifi', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='lodge.amenity'),
        ),
    ]
