# Generated by Django 5.2.15 on 2026-07-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0006_amenity_room_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='lodge.room')),
            ],
            options={
                'verbose_name': 'Room Gallery Image',
                'verbose_name_plural': 'Room Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
